# Generated by Django 6.0 on 2025-12-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('tpo', 'Placement Head'), ('recruiter', 'Recruiter')], default='student', max_length=20),
        ),
    ]
